### ISSUE TITLE
Upgrade processing results in an always-present message

### ISSUE THREAD

**Issue by lat9** [DivaVocals/zen_Image-Handler#151]
As identified in [this](https://www.zen-cart.com/showthread.php?222983-Image-Handler-5-(for-v1-5-5)-Support-Thread&p=1356697#post1356697) Zen Cart support-thread posting, if a previous version of IH is installed ... that doesn't include an `IH_VERSION` but **does** include an `IH_RESIZE` setting, the upgrade processing fails.

The issue is that the upgrade step where the `IH_VERSION` is created/updated doesn't account for the above condition.

**Comment by Pan2020** [comment]
So I tested on 2 cases.

Case 1: Just upgrade in-place via file replacement without updating database.

This notice appears -> https://i.imgur.com/nzFGaN4.png
Then it disappeared!
The interesting is that updated from v.?.?.? as if it was not detected anything
(possibly due to missing values)

Case 2: Do whole DB update, complete `zc_install` update, then login to admin for IH update.

The green stacks appear -> https://i.imgur.com/U65z8SF.png
Then it disappeared!
No mystery version numbering!

However, no matter which ever case it is... this bug of overlapping button is still exist... surely you may have to make a new Github topic for it...
https://i.imgur.com/l7gij13.png

**Comment by lat9** [comment]
Yes, that 'updated from `?.?.?` is based on the detection of preexisting IH settings without an associated `IH_VERSION`.  I'll need some time to investigate that overlapping button issue.
