### ISSUE TITLE
Is the mixed-case file-extensions processing really needed?

### ISSUE THREAD

**Issue by lat9** [DivaVocals/zen_Image-Handler#89]
Within `/includes/extra_configures/bmz_image_handler_conf.php`, there's a definition:

> $ihConf['allow_mixed_case_ext']` = false;

Does anyone ever set this to `true`?  Looking for additional simplifications.

**Comment by Zen4All** [comment]
I do not think so. If it is not a configurable setting through the admin, most people won't know it exists.

**Comment by DivaVocals** [comment]
I would agree.. and as an FYI, I'll add that there are a number of these kinds of configuration options in Tim Kroger's code. There used to be a detailed document explaining their usage on Tim's site though I'm sure it's LONG gone.. Tim's sight was my source for the IH users docs because when I stuck my nose into IH it was to improve the (then) non-existent user docs.

**Comment by DivaVocals** [comment]
That said, it might be a useful option for ADVANCED users. It makes sense that these "options" shoul be available from the admin UI..

**Comment by lat9** [comment]
@DivaVocals, I'm looking to _simplify_ ... not expand the available admin-configured options!  I guess I'll leave that processing alone.

**Comment by Zen4All** [comment]
:rofl:

**Comment by DivaVocals** [comment]
@lat9 oh I GET IT!! lol.. Was just suggesting that these "hidden" configuration items may still have value.. I think Tim's intent was that they were supposed to be for ADVANCED users which is why he left them embedded in the code..
